apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp-deployment
  labels:
    app: rubyapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
      - name: rubyapp
        image: gabrielmalakias/ruby_app
        ports:
        - name: rubyapp-port
          containerPort: 4567
