apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elixirapp-nodeaffinity
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: elixirapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - dev
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: team
                operator: In
                values:
                - dev-team
      containers:
      - name: elixirapp
        image: gabrielmalakias/elixir_app
        ports:
        - name: elixirapp-port
          containerPort: 4000
