apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50



