apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
  labels:
    app: hpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: hpa
        image: gcr.io/google_containers/hpa-example
        ports:
          - name: http-port
            containerPort: 80
        resources:
          requests:
           cpu: 200m
