apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: production
spec:
  limits:
  - default:
      cpu: 200m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 512m
    type: Container


