apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp-deployment-with-quotas
  namespace: production
  labels:
    app: rubyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
      - name: rubyapp
        image: gabrielmalakias/ruby_app
        ports:
        - containerPort: 4567
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi
