apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby_app-deployment
  labels:
    app: rubyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
      - name: rubyapp
        image: gabrielmalakias/ruby_app
        ports:
        - name: klab-port
          containerPort: 4567
      nodeSelector:
        environment: dev
