apiVersion: v1
kind: Pod
metadata:
  name: rubyapp
  labels:
    app: rubyapp
spec:
  containers:
  - name: rubyapp
    image: gabrielmalakias/ruby_app:1
    ports:
    - name: klab-port
      containerPort: 4567
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: password
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username
