apiVersion: v1
kind: Pod
metadata:
  name: kuberneteslab
  labels:
    app: kuberneteslab
spec:
  containers:
  - name: kuberneteslab
    image: gabrielmalakias/kuberneteslab:4
    ports:
    - name: klab-port
      containerPort: 4567
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: password
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username
