apiVersion: v1
kind: Service
metadata:
  name: service-kuberneteslab
spec:
 ports:
   - port: 31000
     nodePort: 31000
     targetPort: klab-port
     protocol: TCP
 selector:
   app: kuberneteslab
 type: NodePort

