apiVersion: v1
kind: Pod
metadata:
  name: ruby_app
  labels:
    app: ruby_app
spec:
  containers:
  - name: ruby_app
    image: gabrielmalakias/ruby_app:1
    ports:
    - name: klab-port
      containerPort: 4567
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: password
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username
