apiVersion: v1
kind: Pod
metadata:
  name: elixirapp
  labels:
    app: elixirapp
spec:
  containers:
  - name: elixirapp
    image: gabrielmalakias/elixir_app
    ports:
    - name: elixirapp-port
      containerPort: 4000
