apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp-deployment
  labels:
    app: rubyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
      - name: rubyapp
        image: gabrielmalakias/ruby_app
        ports:
        - containerPort: 4567
        env:
          - name: ELIXIR_APP_SERVICE_HOST
            value: elixirapp-service
