apiVersion: v1
kind: ReplicationController
metadata:
  name: rubyapp
  labels:
    app: rubyapp
spec:
  replicas: 2
  selector:
    app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
      - name: rubyapp
        image: gabrielmalakias/ruby_app
        ports:
        - name: klab-port
          containerPort: 4567
