apiVersion: v1
kind: Pod
metadata:
  name: ruby_app
  labels:
    app: rubyapp
spec:
  containers:
  - name: rubyapp
    image: gabrielmalakias/ruby_app
    ports:
    - name: klab-port
      containerPort: 4567
