apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: share-credential
spec:
  selector:
    matchLabels:
      environment: production
  env:
    - name: SECRET
      value: "777777"
